# Generated by Django 2.0.13 on 2019-11-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnGrammar', models.CharField(max_length=300)),
                ('photoName', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('grammar', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('pressName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pressUrl', models.CharField(max_length=200)),
                ('urlParameter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('reIndex', models.IntegerField(primary_key=True, serialize=False)),
                ('searchUrl', models.CharField(max_length=200)),
                ('truth', models.BooleanField()),
                ('newsDate', models.DateField()),
                ('content', models.TextField()),
                ('pressName', models.ForeignKey(db_column='pressName', on_delete=django.db.models.deletion.CASCADE, to='news.Press')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='userId',
            field=models.ForeignKey(db_column='userId', default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='news.Users'),
        ),
        migrations.AddField(
            model_name='fakenews',
            name='fnIndex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.Record'),
        ),
    ]
